package notifications

import (
	"database/sql"
	"log/slog"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/google/uuid"
	"itopshub/backend/internal/reqctx"
	"itopshub/backend/internal/response"
)

// Notification types (spec section 35).
const (
	TypeNewTicket            = "NEW_TICKET"
	TypeAssigned             = "ASSIGNED"
	TypeComment              = "COMMENT"
	TypeSLAWarning           = "SLA_WARNING"
	TypeSLACritical          = "SLA_CRITICAL"
	TypeSLABreached          = "SLA_BREACHED"
	TypeFollowUp             = "FOLLOW_UP"
	TypeEscalation           = "ESCALATION"
	TypeUATFailed            = "UAT_FAILED"
	TypeUATPassed            = "UAT_PASSED"
	TypePreProdFailed        = "PRE_PROD_FAILED"
	TypePreProdPassed        = "PRE_PROD_PASSED"
	TypeProductionDeployment = "PRODUCTION_DEPLOYMENT"
	TypeResolved             = "RESOLVED"
)

type Notification struct {
	ID         string    `json:"id"`
	UserID     string    `json:"userId"`
	Type       string    `json:"type"`
	Title      string    `json:"title"`
	Message    string    `json:"message"`
	EntityType string    `json:"entityType"`
	EntityID   string    `json:"entityId"`
	IsRead     bool      `json:"isRead"`
	CreatedAt  time.Time `json:"createdAt"`
}

type Repository struct {
	db *sql.DB
}

func NewRepository(db *sql.DB) *Repository {
	return &Repository{db: db}
}

// Create inserts a new notification for a single user. This is called by
// ticket handlers (assignment, comments) and by the follow-up/escalation
// background workers — it's the single real notification-creation path used
// throughout the app, per spec section 35 ("must be generated by the actual
// notification engine").
func (r *Repository) Create(userID, notifType, title, message, entityType, entityID string) error {
	if userID == "" {
		return nil // no recipient (e.g. unassigned ticket) — nothing to notify
	}
	_, err := r.db.Exec(
		`INSERT INTO notifications (id, user_id, type, title, message, entity_type, entity_id, is_read, created_at)
		 VALUES (?, ?, ?, ?, ?, ?, ?, 0, ?)`,
		"notif-"+uuid.NewString(), userID, notifType, title, message, entityType, entityID, time.Now().UTC(),
	)
	return err
}

func (r *Repository) ListForUser(userID string, unreadOnly bool, limit int) ([]*Notification, error) {
	if limit <= 0 || limit > 200 {
		limit = 50
	}
	query := `SELECT id, user_id, type, title, message, entity_type, entity_id, is_read, created_at
	          FROM notifications WHERE user_id = ?`
	args := []interface{}{userID}
	if unreadOnly {
		query += ` AND is_read = 0`
	}
	query += ` ORDER BY created_at DESC LIMIT ?`
	args = append(args, limit)

	rows, err := r.db.Query(query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := make([]*Notification, 0)
	for rows.Next() {
		var n Notification
		var isRead int
		var createdAt string
		if err := rows.Scan(&n.ID, &n.UserID, &n.Type, &n.Title, &n.Message, &n.EntityType, &n.EntityID, &isRead, &createdAt); err != nil {
			return nil, err
		}
		n.IsRead = isRead != 0
		n.CreatedAt, _ = time.Parse(time.RFC3339, normalizeTime(createdAt))
		out = append(out, &n)
	}
	return out, nil
}

func (r *Repository) UnreadCount(userID string) (int, error) {
	var n int
	err := r.db.QueryRow(`SELECT COUNT(*) FROM notifications WHERE user_id = ? AND is_read = 0`, userID).Scan(&n)
	return n, err
}

func (r *Repository) MarkRead(id, userID string) error {
	_, err := r.db.Exec(`UPDATE notifications SET is_read = 1 WHERE id = ? AND user_id = ?`, id, userID)
	return err
}

func (r *Repository) MarkAllRead(userID string) error {
	_, err := r.db.Exec(`UPDATE notifications SET is_read = 1 WHERE user_id = ?`, userID)
	return err
}

func normalizeTime(v string) string {
	if len(v) == 19 && v[10] == ' ' {
		return v[:10] + "T" + v[11:] + "Z"
	}
	return v
}

// --- HTTP handlers ---

type Handler struct {
	repo   *Repository
	logger *slog.Logger
}

func NewHandler(repo *Repository, logger *slog.Logger) *Handler {
	return &Handler{repo: repo, logger: logger}
}

func (h *Handler) List(w http.ResponseWriter, r *http.Request) {
	userID := reqctx.UserID(r)
	unreadOnly := r.URL.Query().Get("unread") == "true"
	list, err := h.repo.ListForUser(userID, unreadOnly, 100)
	if err != nil {
		response.Internal(w, h.logger, err, "notifications.list")
		return
	}
	response.JSON(w, http.StatusOK, list)
}

func (h *Handler) UnreadCount(w http.ResponseWriter, r *http.Request) {
	userID := reqctx.UserID(r)
	count, err := h.repo.UnreadCount(userID)
	if err != nil {
		response.Internal(w, h.logger, err, "notifications.unreadcount")
		return
	}
	response.JSON(w, http.StatusOK, map[string]int{"count": count})
}

func (h *Handler) MarkRead(w http.ResponseWriter, r *http.Request) {
	id := chi.URLParam(r, "id")
	userID := reqctx.UserID(r)
	if err := h.repo.MarkRead(id, userID); err != nil {
		response.Internal(w, h.logger, err, "notifications.markread")
		return
	}
	response.JSON(w, http.StatusOK, map[string]bool{"ok": true})
}

func (h *Handler) MarkAllRead(w http.ResponseWriter, r *http.Request) {
	userID := reqctx.UserID(r)
	if err := h.repo.MarkAllRead(userID); err != nil {
		response.Internal(w, h.logger, err, "notifications.markallread")
		return
	}
	response.JSON(w, http.StatusOK, map[string]bool{"ok": true})
}
